pr:
  - main

jobs:
  - job: Lint
    displayName: 'Lint Code'
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 10

    steps:
      - checkout: self
        fetchDepth: 0
      - script: |
          echo "Running lint checks..."
          npm run lint
        displayName: 'Run Lint Checks'