services:
  app:
    image: receitas:v1
    container_name: nestjs-app
    ports:
      - "3000:3000" 
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: