services:
  app:
    image: receitas:v1
    container_name: nestjs-app
    ports:
      - "3000:3000" 
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    entrypoint: ["sh", "-c", "npx prisma migrate deploy && node dist/main.js"]
  db:
    image: postgres:15
    container_name: postgres-db
    ports: 
    # redireciona para 5433 para evitar conflito com o postgres local
      - "5433:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: